import { getDb } from "../api/queries/connection";
import { companies, categories, products, inventory } from "./schema";
import { sql } from "drizzle-orm";

/**
 * FreshFlow Development Seed Data
 * Run with: npx tsx db/seed.ts
 */

async function seed() {
  const db = getDb();
  console.log("🌱 Seeding FreshFlow database...\n");

  // Clear existing data (in correct order for FK constraints)
  console.log("Clearing existing data...");
  await db.delete(inventory);
  await db.delete(products);
  await db.delete(categories);
  await db.delete(companies);
  console.log("  ✓ Existing data cleared");

  // ─── Companies ───
  console.log("Creating companies...");
  const companyData = [
    {
      name: "Tex’s Chicken & Burgers",
      slug: "texs-chicken-and-burgers",
      type: "supplier" as const,
      description: "Worth Every Bite",
      logo: "/branding/logo.png",
      email: "contact@texschickenandburgers.com",
      phone: "+1 (212) 555-0199",
      addressLine1: "Tex’s Kitchen",
      city: "New York",
      state: "NY",
      postalCode: "10001",
      country: "USA",
      isVerified: true,
      isActive: true,
      minimumOrderAmount: "0.00",
      paymentTerms: "net_30" as const,
    },
    {
      name: "Tropical Direct Wholesale",
      slug: "tropical-direct-wholesale",
      type: "supplier" as const,
      description: "Premium tropical fruit importer and distributor serving the North American market since 2008.",
      email: "sales@tropicaldirect.com",
      phone: "+1 (305) 555-0101",
      addressLine1: "4500 NW 36th St",
      city: "Miami",
      state: "FL",
      postalCode: "33166",
      country: "USA",
      isVerified: true,
      isActive: true,
      minimumOrderAmount: "500.00",
      paymentTerms: "net_30" as const,
    },
    {
      name: "Citrus Kings Supply Co.",
      slug: "citrus-kings-supply",
      type: "supplier" as const,
      description: "Family-owned citrus grower and packer from California's Central Valley. Specializing in oranges, lemons, and grapefruits.",
      email: "orders@citruskings.com",
      phone: "+1 (559) 555-0202",
      addressLine1: "8800 S Fruit Ave",
      city: "Fresno",
      state: "CA",
      postalCode: "93706",
      country: "USA",
      isVerified: true,
      isActive: true,
      minimumOrderAmount: "300.00",
      paymentTerms: "net_15" as const,
    },
    {
      name: "Berry Fresh Farms",
      slug: "berry-fresh-farms",
      type: "supplier" as const,
      description: "Organic berry specialist growing strawberries, blueberries, and raspberries in the Pacific Northwest.",
      email: "wholesale@berryfresh.com",
      phone: "+1 (503) 555-0303",
      addressLine1: "1200 NW Berry Rd",
      city: "Hillsboro",
      state: "OR",
      postalCode: "97124",
      country: "USA",
      isVerified: true,
      isActive: true,
      minimumOrderAmount: "250.00",
      paymentTerms: "net_30" as const,
    },
    {
      name: "GreenGrocer Market Chain",
      slug: "greengrocer-market",
      type: "buyer" as const,
      description: "Regional grocery chain with 45 stores across the Pacific Northwest. Focus on fresh, locally-sourced produce.",
      email: "procurement@greengrocer.com",
      phone: "+1 (206) 555-0404",
      addressLine1: "800 Elliott Ave",
      city: "Seattle",
      state: "WA",
      postalCode: "98109",
      country: "USA",
      isVerified: true,
      isActive: true,
      minimumOrderAmount: "0.00",
      paymentTerms: "net_45" as const,
    },
    {
      name: "Metro Restaurant Supply",
      slug: "metro-restaurant-supply",
      type: "buyer" as const,
      description: "Wholesale supplier to over 200 restaurants, hotels, and catering companies in the metropolitan area.",
      email: "buying@metrorestaurantsupply.com",
      phone: "+1 (212) 555-0505",
      addressLine1: "250 W 39th St",
      city: "New York",
      state: "NY",
      postalCode: "10018",
      country: "USA",
      isVerified: true,
      isActive: true,
      minimumOrderAmount: "0.00",
      paymentTerms: "net_30" as const,
    },
    {
      name: "Global Fruit Traders LLC",
      slug: "global-fruit-traders",
      type: "both" as const,
      description: "International fruit trading company. We both source from growers and distribute to retailers worldwide.",
      email: "trade@globalfruit.com",
      phone: "+1 (973) 555-0606",
      addressLine1: "1 Port Newark Way",
      city: "Newark",
      state: "NJ",
      postalCode: "07114",
      country: "USA",
      isVerified: true,
      isActive: true,
      minimumOrderAmount: "1000.00",
      paymentTerms: "net_30" as const,
    },
  ];

  for (const c of companyData) {
    await db.insert(companies).values(c);
  }
  console.log(`  ✓ ${companyData.length} companies created`);

  // ─── Categories ───
  console.log("Creating categories...");
  const categoryData = [
    { name: "Citrus", slug: "citrus", description: "Oranges, lemons, limes, grapefruits, and other citrus fruits", icon: "citrus", color: "#F59E0B", sortOrder: 1, isActive: true },
    { name: "Tropical", slug: "tropical", description: "Mangoes, pineapples, bananas, coconuts, and exotic tropical fruits", icon: "tropical", color: "#10B981", sortOrder: 2, isActive: true },
    { name: "Berries", slug: "berries", description: "Strawberries, blueberries, raspberries, blackberries, and more", icon: "berries", color: "#8B5CF6", sortOrder: 3, isActive: true },
    { name: "Stone Fruits", slug: "stone-fruits", description: "Peaches, plums, cherries, apricots, nectarines", icon: "cherry", color: "#F43F5E", sortOrder: 4, isActive: true },
    { name: "Melons", slug: "melons", description: "Watermelons, cantaloupes, honeydews, and specialty melons", icon: "melon", color: "#06B6D4", sortOrder: 5, isActive: true },
    { name: "Apples & Pears", slug: "apples-pears", description: "All varieties of apples, pears, and related pomme fruits", icon: "apple", color: "#EF4444", sortOrder: 6, isActive: true },
    { name: "Grapes", slug: "grapes", description: "Table grapes, wine grapes, and specialty varieties", icon: "grapes", color: "#7C3AED", sortOrder: 7, isActive: true },
    { name: "Exotic & Specialty", slug: "exotic-specialty", description: "Dragon fruit, jackfruit, rambutan, and other specialty items", icon: "star", color: "#EC4899", sortOrder: 8, isActive: true },
  ];

  for (const c of categoryData) {
    await db.insert(categories).values(c);
  }
  console.log(`  ✓ ${categoryData.length} categories created`);

  // ─── Products ───
  console.log("Creating products...");
  const productData = [
    {
      name: "Valencia Oranges",
      slug: "valencia-oranges",
      description: "Premium Valencia oranges, known for their sweet flavor and juiciness. Perfect for fresh juice and retail. Each case contains 88 count, approximately 40 lbs.",
      shortDescription: "Sweet, juicy Valencia oranges perfect for juicing",
      categoryId: 1,
      supplierId: 2,
      unitPrice: "32.50",
      compareAtPrice: "38.00",
      unitType: "case" as const,
      unitSize: "88 count / 40 lbs",
      minimumOrderQuantity: 5,
      image: "https://images.unsplash.com/photo-1547514701-42782101795e?w=600&h=400&fit=crop",
      origin: "California, USA",
      season: "March - September",
      grade: "grade_a" as const,
      organic: false,
      certifications: '["GFSI", "California Grown"]',
      status: "active" as const,
      tags: "oranges, citrus, valencia, juice, california",
    },
    {
      name: "Organic Navel Oranges",
      slug: "organic-navel-oranges",
      description: "Certified organic navel oranges with easy-peel skin and seedless interior. Ideal snacking orange with exceptional sweetness.",
      shortDescription: "Certified organic, seedless, easy-peel navel oranges",
      categoryId: 1,
      supplierId: 2,
      unitPrice: "45.00",
      compareAtPrice: "52.00",
      unitType: "case" as const,
      unitSize: "56 count / 38 lbs",
      minimumOrderQuantity: 3,
      image: "https://images.unsplash.com/photo-1582979512210-99b6a53386f9?w=600&h=400&fit=crop",
      origin: "California, USA",
      season: "November - June",
      grade: "premium" as const,
      organic: true,
      certifications: '["USDA Organic", "California Grown", "Non-GMO"]',
      status: "active" as const,
      tags: "oranges, navel, organic, citrus, seedless",
    },
    {
      name: "Eureka Lemons",
      slug: "eureka-lemons",
      description: "Bright yellow Eureka lemons with high acidity and strong flavor. Consistent quality year-round. Popular for culinary and beverage applications.",
      shortDescription: "Bright yellow, high-acid lemons for culinary use",
      categoryId: 1,
      supplierId: 2,
      unitPrice: "28.00",
      compareAtPrice: "32.00",
      unitType: "case" as const,
      unitSize: "115 count / 40 lbs",
      minimumOrderQuantity: 5,
      image: "https://images.unsplash.com/photo-1609842947419-ba4f04d5d60f?w=600&h=400&fit=crop",
      origin: "California, USA",
      season: "Year-round",
      grade: "grade_a" as const,
      organic: false,
      certifications: '["GFSI"]',
      status: "active" as const,
      tags: "lemons, eureka, citrus, culinary",
    },
    {
      name: "Kent Mangoes",
      slug: "kent-mangoes",
      description: "Sweet and fiberless Kent mangoes with rich golden flesh. Perfect for fresh consumption, smoothies, and desserts.",
      shortDescription: "Sweet, fiberless Kent mangoes with golden flesh",
      categoryId: 2,
      supplierId: 1,
      unitPrice: "18.75",
      compareAtPrice: "22.00",
      unitType: "case" as const,
      unitSize: "12 count / 9 lbs",
      minimumOrderQuantity: 10,
      image: "https://images.unsplash.com/photo-1553279768-865429fa0078?w=600&h=400&fit=crop",
      origin: "Mexico",
      season: "January - September",
      grade: "premium" as const,
      organic: false,
      certifications: '["GlobalGAP"]',
      status: "active" as const,
      tags: "mangoes, kent, tropical, mexico",
    },
    {
      name: "Organic Hass Avocados",
      slug: "organic-hass-avocados",
      description: "Creamy, buttery organic Hass avocados. Consistent quality with excellent shelf life. Perfect for retail and food service.",
      shortDescription: "Creamy organic Hass avocados with excellent shelf life",
      categoryId: 2,
      supplierId: 1,
      unitPrice: "42.00",
      compareAtPrice: "48.00",
      unitType: "case" as const,
      unitSize: "48 count / 25 lbs",
      minimumOrderQuantity: 4,
      image: "https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=600&h=400&fit=crop",
      origin: "Mexico",
      season: "Year-round",
      grade: "grade_a" as const,
      organic: true,
      certifications: '["USDA Organic", "Fair Trade", "GlobalGAP"]',
      status: "active" as const,
      tags: "avocados, hass, organic, tropical, mexico",
    },
    {
      name: "Golden Pineapples",
      slug: "golden-pineapples",
      description: "Extra sweet golden pineapples with vibrant yellow flesh. Low acidity, high Brix. Ideal for fresh cut and juicing.",
      shortDescription: "Extra sweet golden pineapples, low acidity",
      categoryId: 2,
      supplierId: 1,
      unitPrice: "22.00",
      compareAtPrice: "26.00",
      unitType: "case" as const,
      unitSize: "7 count / 35 lbs",
      minimumOrderQuantity: 5,
      image: "https://images.unsplash.com/photo-1550258987-190a2d41a8ba?w=600&h=400&fit=crop",
      origin: "Costa Rica",
      season: "Year-round",
      grade: "grade_a" as const,
      organic: false,
      certifications: '["Rainforest Alliance", "GlobalGAP"]',
      status: "active" as const,
      tags: "pineapples, golden, tropical, costa rica",
    },
    {
      name: "Organic Strawberries",
      slug: "organic-strawberries",
      description: "Plump, sweet organic strawberries with vibrant red color. Grown in the fertile Willamette Valley. Excellent shelf life.",
      shortDescription: "Sweet, plump organic strawberries from Oregon",
      categoryId: 3,
      supplierId: 3,
      unitPrice: "36.00",
      compareAtPrice: "42.00",
      unitType: "case" as const,
      unitSize: "8 flats / 12 lbs",
      minimumOrderQuantity: 5,
      image: "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=600&h=400&fit=crop",
      origin: "Oregon, USA",
      season: "April - October",
      grade: "premium" as const,
      organic: true,
      certifications: '["USDA Organic", "Oregon Tilth"]',
      status: "active" as const,
      tags: "strawberries, berries, organic, oregon",
    },
    {
      name: "Blueberries Jumbo",
      slug: "blueberries-jumbo",
      description: "Extra-large jumbo blueberries with excellent sweetness and firm texture. Perfect for retail premium packs and baking.",
      shortDescription: "Jumbo blueberries, extra-large and sweet",
      categoryId: 3,
      supplierId: 3,
      unitPrice: "48.00",
      compareAtPrice: "55.00",
      unitType: "case" as const,
      unitSize: "12 pints / 6 lbs",
      minimumOrderQuantity: 8,
      image: "https://images.unsplash.com/photo-1498557850523-fd3d118b962e?w=600&h=400&fit=crop",
      origin: "Oregon, USA",
      season: "June - September",
      grade: "premium" as const,
      organic: false,
      certifications: '["USDA Organic eligible", "GAP"]',
      status: "active" as const,
      tags: "blueberries, jumbo, berries, oregon",
    },
    {
      name: "Yellow Peaches",
      slug: "yellow-peaches",
      description: "Tree-ripened yellow peaches with juicy, sweet flesh. Perfect balance of sugar and acid. Great for fresh and canning.",
      shortDescription: "Tree-ripened, juicy yellow peaches",
      categoryId: 4,
      supplierId: 2,
      unitPrice: "28.50",
      compareAtPrice: "34.00",
      unitType: "case" as const,
      unitSize: "48 count / 25 lbs",
      minimumOrderQuantity: 5,
      image: "https://images.unsplash.com/photo-1528821128474-27f963b062bf?w=600&h=400&fit=crop",
      origin: "California, USA",
      season: "May - September",
      grade: "grade_a" as const,
      organic: false,
      certifications: '["California Grown"]',
      status: "active" as const,
      tags: "peaches, stone fruit, yellow, california",
    },
    {
      name: "Watermelon Seedless",
      slug: "watermelon-seedless",
      description: "Large, oblong seedless watermelons with deep red, crisp flesh. High Brix, excellent shipping quality.",
      shortDescription: "Large seedless watermelons with deep red flesh",
      categoryId: 5,
      supplierId: 2,
      unitPrice: "15.00",
      compareAtPrice: "18.00",
      unitType: "each" as const,
      unitSize: "18-22 lbs avg",
      minimumOrderQuantity: 20,
      image: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=600&h=400&fit=crop",
      origin: "Texas, USA",
      season: "May - August",
      grade: "grade_a" as const,
      organic: false,
      certifications: '["Texas Department of Agriculture"]',
      status: "active" as const,
      tags: "watermelon, melon, seedless, texas",
    },
    {
      name: "Honeycrisp Apples",
      slug: "honeycrisp-apples",
      description: "Premium Honeycrisp apples with explosive crunch and juicily sweet flavor. Consumer favorite, high retail demand.",
      shortDescription: "Premium Honeycrisp, explosively crunchy and sweet",
      categoryId: 6,
      supplierId: 6,
      unitPrice: "52.00",
      compareAtPrice: "60.00",
      unitType: "case" as const,
      unitSize: "100 count / 40 lbs",
      minimumOrderQuantity: 5,
      image: "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=600&h=400&fit=crop",
      origin: "Washington, USA",
      season: "September - April",
      grade: "premium" as const,
      organic: false,
      certifications: '["Washington State Apple Commission"]',
      status: "active" as const,
      tags: "apples, honeycrisp, washington, premium",
    },
    {
      name: "Red Seedless Grapes",
      slug: "red-seedless-grapes",
      description: "Crisp, sweet red seedless grapes with excellent shelf life and attractive color. Popular retail variety.",
      shortDescription: "Crisp, sweet red seedless grapes",
      categoryId: 7,
      supplierId: 6,
      unitPrice: "24.50",
      compareAtPrice: "29.00",
      unitType: "case" as const,
      unitSize: "18 lbs",
      minimumOrderQuantity: 10,
      image: "https://images.unsplash.com/photo-1537640538966-79f369143f8f?w=600&h=400&fit=crop",
      origin: "California, USA",
      season: "June - December",
      grade: "grade_a" as const,
      organic: false,
      certifications: '["California Grown"]',
      status: "active" as const,
      tags: "grapes, red, seedless, california",
    },
    {
      name: "Dragon Fruit (Pitaya)",
      slug: "dragon-fruit-pitaya",
      description: "Stunning magenta dragon fruit with white flesh and tiny black seeds. Mild sweetness, kiwi-like texture. Instagram-worthy presentation.",
      shortDescription: "Vibrant magenta dragon fruit with white flesh",
      categoryId: 8,
      supplierId: 1,
      unitPrice: "48.00",
      compareAtPrice: "55.00",
      unitType: "case" as const,
      unitSize: "10 count / 8 lbs",
      minimumOrderQuantity: 3,
      image: "https://images.unsplash.com/photo-1527325678964-54921661f888?w=600&h=400&fit=crop",
      origin: "Vietnam",
      season: "Year-round",
      grade: "grade_a" as const,
      organic: false,
      certifications: '["GlobalGAP", "VietGAP"]',
      status: "active" as const,
      tags: "dragon fruit, pitaya, exotic, vietnam, specialty",
    },
  ];

  for (const p of productData) {
    await db.insert(products).values(p);
  }
  console.log(`  ✓ ${productData.length} products created`);

  // ─── Inventory ───
  console.log("Creating inventory records...");
  const inventoryData = [
    { productId: 1, supplierId: 2, quantityOnHand: 500, quantityReserved: 50, quantityAvailable: 450, reorderLevel: 100, reorderQuantity: 200, warehouseLocation: "CA-FRESNO-A12", status: "in_stock" as const },
    { productId: 2, supplierId: 2, quantityOnHand: 120, quantityReserved: 15, quantityAvailable: 105, reorderLevel: 50, reorderQuantity: 100, warehouseLocation: "CA-FRESNO-A14", status: "in_stock" as const },
    { productId: 3, supplierId: 2, quantityOnHand: 800, quantityReserved: 80, quantityAvailable: 720, reorderLevel: 150, reorderQuantity: 300, warehouseLocation: "CA-FRESNO-B01", status: "in_stock" as const },
    { productId: 4, supplierId: 1, quantityOnHand: 200, quantityReserved: 45, quantityAvailable: 155, reorderLevel: 80, reorderQuantity: 150, warehouseLocation: "FL-MIAMI-T03", status: "low_stock" as const },
    { productId: 5, supplierId: 1, quantityOnHand: 350, quantityReserved: 30, quantityAvailable: 320, reorderLevel: 100, reorderQuantity: 200, warehouseLocation: "FL-MIAMI-T05", status: "in_stock" as const },
    { productId: 6, supplierId: 1, quantityOnHand: 600, quantityReserved: 60, quantityAvailable: 540, reorderLevel: 120, reorderQuantity: 250, warehouseLocation: "FL-MIAMI-T08", status: "in_stock" as const },
    { productId: 7, supplierId: 3, quantityOnHand: 80, quantityReserved: 25, quantityAvailable: 55, reorderLevel: 60, reorderQuantity: 100, warehouseLocation: "OR-HILLS-C02", status: "low_stock" as const },
    { productId: 8, supplierId: 3, quantityOnHand: 150, quantityReserved: 20, quantityAvailable: 130, reorderLevel: 40, reorderQuantity: 80, warehouseLocation: "OR-HILLS-C04", status: "in_stock" as const },
    { productId: 9, supplierId: 2, quantityOnHand: 250, quantityReserved: 40, quantityAvailable: 210, reorderLevel: 80, reorderQuantity: 150, warehouseLocation: "CA-FRESNO-D06", status: "in_stock" as const },
    { productId: 10, supplierId: 2, quantityOnHand: 100, quantityReserved: 10, quantityAvailable: 90, reorderLevel: 30, reorderQuantity: 60, warehouseLocation: "CA-FRESNO-D10", status: "in_stock" as const },
    { productId: 11, supplierId: 6, quantityOnHand: 400, quantityReserved: 75, quantityAvailable: 325, reorderLevel: 100, reorderQuantity: 200, warehouseLocation: "NJ-NEWARK-F01", status: "in_stock" as const },
    { productId: 12, supplierId: 6, quantityOnHand: 300, quantityReserved: 50, quantityAvailable: 250, reorderLevel: 80, reorderQuantity: 150, warehouseLocation: "NJ-NEWARK-F03", status: "in_stock" as const },
    { productId: 13, supplierId: 1, quantityOnHand: 45, quantityReserved: 15, quantityAvailable: 30, reorderLevel: 30, reorderQuantity: 60, warehouseLocation: "FL-MIAMI-T12", status: "low_stock" as const },
  ];

  for (const inv of inventoryData) {
    await db.insert(inventory).values(inv);
  }
  console.log(`  ✓ ${inventoryData.length} inventory records created`);

  console.log("\n✅ FreshFlow seed complete!");
}

seed().catch((err) => {
  console.error("❌ Seed failed:", err);
  process.exit(1);
});
