import { Pool } from "pg";
import { drizzle } from "drizzle-orm/node-postgres";
import * as schema from "../db/schema";
import { sql } from "drizzle-orm";

const connectionString = process.env.DATABASE_URL;
if (!connectionString) {
  console.error("No DATABASE_URL found");
  process.exit(1);
}

const pool = new Pool({
  connectionString,
  ssl: { rejectUnauthorized: false },
});

const db = drizzle(pool, { schema });

async function seed() {
  console.log("🌱 Seeding Shah's Halal Food catalog into PostgreSQL...");

  // 1. Clear existing inventory, products, categories, companies
  await db.execute(sql`DELETE FROM inventory`);
  await db.execute(sql`DELETE FROM cart_items`);
  await db.execute(sql`DELETE FROM order_items`);
  await db.execute(sql`DELETE FROM products`);
  await db.execute(sql`DELETE FROM categories`);
  await db.execute(sql`DELETE FROM companies WHERE slug = 'shahs-halal' OR slug = 'fresh-farms-direct'`);

  // 2. Insert Shah's Halal Company
  const [shahsCompany] = await db
    .insert(schema.companies)
    .values({
      name: "Shah's Halal Food",
      slug: "shahs-halal",
      type: "supplier",
      description: "Authentic certified Halal food cart & restaurant. Fresh platters, gyros, burgers, wings, and sides.",
      email: "info@shahshalalfood.com",
      phone: "+1 (718) 555-0199",
      addressLine1: "121-02 Liberty Ave",
      city: "Richmond Hill",
      state: "NY",
      postalCode: "11419",
      country: "USA",
      isVerified: true,
      isActive: true,
      minimumOrderAmount: "0.00",
      paymentTerms: "prepaid",
    })
    .returning();

  const supplierId = shahsCompany.id;
  console.log(`  ✓ Company created: Shah's Halal Food (ID: ${supplierId})`);

  // 3. Insert Categories
  const categoryDefs = [
    {
      name: "Platters",
      slug: "platters",
      description: "Authentic halal meat & falafel served over spiced basmati rice with fresh salad, warm pita, and signature sauces",
      icon: "beef",
      color: "#DC2626",
      sortOrder: 1,
      isActive: true,
    },
    {
      name: "Gyros",
      slug: "gyros",
      description: "Tender halal meats & falafel wrapped in warm fluffy pita bread with crisp lettuce, tomato, cucumber & sauces",
      icon: "package",
      color: "#EA580C",
      sortOrder: 2,
      isActive: true,
    },
    {
      name: "Burgers & Sandwiches",
      slug: "burgers-sandwiches",
      description: "Juicy halal cheeseburgers, crispy chicken, falafel sandwiches, and classic Philly cheesesteaks",
      icon: "sparkles",
      color: "#D97706",
      sortOrder: 3,
      isActive: true,
    },
    {
      name: "Party Wings",
      slug: "party-wings",
      description: "Crispy seasoned chicken wings tossed in your choice of signature sauces (6 pcs)",
      icon: "sparkles",
      color: "#E11D48",
      sortOrder: 4,
      isActive: true,
    },
    {
      name: "Sides",
      slug: "sides",
      description: "Crispy fresh cut fries, pakora chips, golden baklava, hummus & warm pita bread",
      icon: "boxes",
      color: "#059669",
      sortOrder: 5,
      isActive: true,
    },
    {
      name: "Drinks",
      slug: "drinks",
      description: "Refreshing cold sodas, iced tea, Snapple, energy drinks, and bottled water",
      icon: "droplets",
      color: "#0284C7",
      sortOrder: 6,
      isActive: true,
    },
    {
      name: "Catering",
      slug: "catering",
      description: "Large party platters and feast packages for family gatherings, events, and parties",
      icon: "package",
      color: "#7C3AED",
      sortOrder: 7,
      isActive: true,
    },
  ];

  const categoryMap = new Map<string, number>();
  for (const c of categoryDefs) {
    const [inserted] = await db.insert(schema.categories).values(c).returning();
    categoryMap.set(c.slug, inserted.id);
  }
  console.log(`  ✓ ${categoryDefs.length} categories created`);

  // 4. Products List
  const productList = [
    // Platters
    {
      name: "Original Chicken Platter",
      slug: "original-chicken-platter",
      categorySlug: "platters",
      unitPrice: "12.99",
      compareAtPrice: "14.99",
      shortDescription: "Grilled marinated halal chicken over basmati rice with salad, warm pita & Shah's white sauce",
      description: "Our signature original chicken platter. Freshly grilled, seasoned halal chicken served over aromatic spiced basmati rice, accompanied by crisp lettuce, diced tomatoes, fresh cucumbers, a slice of warm pita bread, and Shah's famous white and fiery hot sauces.",
      unitSize: "1 platter",
      image: "/products/chicken-platter.jpg",
      tags: "chicken,platter,rice,halal,signature,best-seller",
      showInFreshDeals: true,
      isFeatured: true,
      displayPriority: 1,
    },
    {
      name: "Chicken Shawarma Platter",
      slug: "chicken-shawarma-platter",
      categorySlug: "platters",
      unitPrice: "12.99",
      compareAtPrice: "14.99",
      shortDescription: "Tender seasoned chicken shawarma shaved fresh over basmati rice and salad",
      description: "Slow-roasted, delicately spiced chicken shawarma carved thin and served over fluffy yellow basmati rice, crisp Mediterranean garden salad, warm pita bread, and our house signature garlic white sauce.",
      unitSize: "1 platter",
      image: "/products/chicken-shawarma-platter.jpg",
      tags: "shawarma,chicken,platter,rice,halal",
      showInFreshDeals: true,
      isFeatured: true,
      displayPriority: 2,
    },
    {
      name: "Beef & Lamb Platter",
      slug: "beef-lamb-platter",
      categorySlug: "platters",
      unitPrice: "13.49",
      compareAtPrice: "15.49",
      shortDescription: "Savory seasoned beef & lamb gyro sliced thin over basmati rice with salad & pita",
      description: "A classic NYC cart favorite. Tender, seasoned beef & lamb gyro meat sliced thin and seared on the grill, served over fragrant basmati rice with freshly tossed salad, pita bread, and Shah's signature white & hot sauces.",
      unitSize: "1 platter",
      image: "/products/beef-lamb-platter.jpg",
      tags: "beef,lamb,gyro,platter,rice,halal",
      showInFreshDeals: true,
      isFeatured: false,
      displayPriority: 3,
    },
    {
      name: "All Lamb Platter",
      slug: "all-lamb-platter",
      categorySlug: "platters",
      unitPrice: "13.99",
      compareAtPrice: "15.99",
      shortDescription: "100% pure tender halal lamb over spiced basmati rice with fresh salad & pita",
      description: "Hearty, 100% pure seasoned halal lamb seared to juicy perfection on the flat top, served over seasoned yellow basmati rice, fresh crisp salad, warm toasted pita, and Shah's famous white and hot sauce.",
      unitSize: "1 platter",
      image: "/products/lamb-platter.jpg",
      tags: "lamb,platter,rice,halal,premium",
      showInFreshDeals: false,
      isFeatured: true,
      displayPriority: 4,
    },
    {
      name: "Combo Over Rice Platter",
      slug: "combo-over-rice-platter",
      categorySlug: "platters",
      unitPrice: "13.49",
      compareAtPrice: "15.49",
      shortDescription: "The best of both worlds: grilled chicken and savory gyro over rice with pita & salad",
      description: "Shah's #1 fan favorite! A generous half-and-half combination of our juicy grilled chicken and seared beef & lamb gyro over hot aromatic basmati rice, served with fresh chopped lettuce, diced tomatoes, pita wedges, and smothered in our iconic white sauce.",
      unitSize: "1 platter",
      image: "/products/combo-platter.jpg",
      tags: "combo,chicken,lamb,gyro,platter,rice,halal,popular",
      showInFreshDeals: true,
      isFeatured: true,
      displayPriority: 5,
    },
    {
      name: "Kofta Kebab Platter",
      slug: "kofta-kebab-platter",
      categorySlug: "platters",
      unitPrice: "13.49",
      compareAtPrice: "15.49",
      shortDescription: "Minced ground beef and lamb kebabs spiced with Middle Eastern herbs over rice",
      description: "Traditional spiced ground beef and lamb kofta kebabs grilled fresh with fragrant herbs and onions, served atop spiced yellow rice with crisp garden salad, warm pita, and white sauce.",
      unitSize: "1 platter",
      image: "/products/kofta-platter.jpg",
      tags: "kofta,kebab,beef,lamb,platter,rice",
      showInFreshDeals: false,
      isFeatured: false,
      displayPriority: 6,
    },
    {
      name: "Falafel Platter (Vegetarian)",
      slug: "falafel-platter",
      categorySlug: "platters",
      unitPrice: "11.99",
      compareAtPrice: "13.99",
      shortDescription: "Crispy golden chickpea falafel patties over spiced basmati rice with salad & pita",
      description: "Golden, crispy vegetarian falafel made from seasoned ground chickpeas, garlic, parsley, and Mediterranean herbs. Served over fragrant basmati rice, fresh crisp salad, toasted pita, and creamy tahini white sauce.",
      unitSize: "1 platter",
      image: "/products/falafel-platter.jpg",
      tags: "falafel,vegetarian,platter,rice,halal",
      showInFreshDeals: true,
      isFeatured: false,
      displayPriority: 7,
    },
    {
      name: "Fish Platter",
      slug: "fish-platter",
      categorySlug: "platters",
      unitPrice: "12.99",
      compareAtPrice: "14.99",
      shortDescription: "Crispy seasoned fish fillets served hot over basmati rice with garden salad & sauce",
      description: "Golden fried seasoned fish fillets served piping hot over seasoned basmati rice with fresh chopped lettuce, tomatoes, cucumbers, warm pita bread, and Shah's signature sauce.",
      unitSize: "1 platter",
      image: "/products/fish-platter.jpg",
      tags: "fish,seafood,platter,rice,halal",
      showInFreshDeals: false,
      isFeatured: false,
      displayPriority: 8,
    },

    // Gyros
    {
      name: "Original Chicken Gyro",
      slug: "original-chicken-gyro",
      categorySlug: "gyros",
      unitPrice: "9.99",
      compareAtPrice: "11.49",
      shortDescription: "Grilled marinated halal chicken wrapped in warm pita with lettuce, tomato & white sauce",
      description: "Tender chunks of marinated grilled halal chicken folded into a warm, fluffy Greek pita with crisp shredded lettuce, diced ripe tomatoes, and drizzled with Shah's famous white and hot sauces.",
      unitSize: "1 gyro wrap",
      image: "/products/chicken-gyro.jpg",
      tags: "chicken,gyro,pita,wrap,halal",
      showInFreshDeals: true,
      isFeatured: true,
      displayPriority: 9,
    },
    {
      name: "Chicken Shawarma Gyro",
      slug: "chicken-shawarma-gyro",
      categorySlug: "gyros",
      unitPrice: "9.99",
      compareAtPrice: "11.49",
      shortDescription: "Spiced shaved chicken shawarma in toasted pita with crunchy vegetables & garlic sauce",
      description: "Juicy, spiced chicken shawarma wrapped inside warm pita bread with crunchy lettuce, ripe tomatoes, pickles, and our signature creamy white sauce.",
      unitSize: "1 gyro wrap",
      image: "/products/shawarma-gyro.jpg",
      tags: "shawarma,chicken,gyro,pita,wrap",
      showInFreshDeals: false,
      isFeatured: false,
      displayPriority: 10,
    },
    {
      name: "Beef & Lamb Gyro",
      slug: "beef-lamb-gyro",
      categorySlug: "gyros",
      unitPrice: "10.49",
      compareAtPrice: "11.99",
      shortDescription: "Savory seared beef & lamb gyro slices wrapped in fluffy pita with salad & sauces",
      description: "Succulent slices of seasoned beef & lamb gyro meat wrapped snugly in a warm pita bread with crunchy lettuce, diced tomatoes, and Shah's secret recipe white sauce.",
      unitSize: "1 gyro wrap",
      image: "/products/beef-lamb-gyro.jpg",
      tags: "beef,lamb,gyro,pita,wrap,halal",
      showInFreshDeals: true,
      isFeatured: true,
      displayPriority: 11,
    },
    {
      name: "All Lamb Gyro",
      slug: "all-lamb-gyro",
      categorySlug: "gyros",
      unitPrice: "10.99",
      compareAtPrice: "12.49",
      shortDescription: "100% pure tender grilled lamb wrapped in warm pita with fresh salad & white sauce",
      description: "Tender seared halal lamb wrapped in soft warm pita with fresh garden salad and our famous savory white and spicy hot sauces.",
      unitSize: "1 gyro wrap",
      image: "/products/lamb-gyro.jpg",
      tags: "lamb,gyro,pita,wrap,halal",
      showInFreshDeals: false,
      isFeatured: false,
      displayPriority: 12,
    },
    {
      name: "Combo Gyro (Chicken & Lamb)",
      slug: "combo-gyro",
      categorySlug: "gyros",
      unitPrice: "10.49",
      compareAtPrice: "11.99",
      shortDescription: "Half grilled chicken, half beef & lamb gyro meat wrapped in warm pita with sauces",
      description: "Can't decide? Enjoy both! Marinated grilled chicken paired with tender beef & lamb gyro, wrapped in warm pita with crisp lettuce, fresh tomatoes, and our signature sauces.",
      unitSize: "1 gyro wrap",
      image: "/products/combo-gyro.jpg",
      tags: "combo,chicken,lamb,gyro,pita,wrap",
      showInFreshDeals: true,
      isFeatured: true,
      displayPriority: 13,
    },
    {
      name: "Kofta Kebab Gyro",
      slug: "kofta-kebab-gyro",
      categorySlug: "gyros",
      unitPrice: "10.49",
      compareAtPrice: "11.99",
      shortDescription: "Herbed ground beef and lamb kebab wrapped in warm pita with salad & garlic white sauce",
      description: "Savory minced meat kebab grilled on skewers, tucked into warm toasted pita bread with shredded lettuce, diced tomatoes, and aromatic white sauce.",
      unitSize: "1 gyro wrap",
      image: "/products/kofta-gyro.jpg",
      tags: "kofta,kebab,gyro,pita,wrap",
      showInFreshDeals: false,
      isFeatured: false,
      displayPriority: 14,
    },
    {
      name: "Falafel Gyro (Vegetarian)",
      slug: "falafel-gyro",
      categorySlug: "gyros",
      unitPrice: "8.99",
      compareAtPrice: "10.49",
      shortDescription: "Crispy freshly fried falafel patties wrapped in warm pita with lettuce, tomato & tahini",
      description: "Crisp, golden-brown falafel patties gently crushed into warm pita bread, topped with shredded lettuce, ripe tomatoes, and drizzled with smooth tahini and white sauce.",
      unitSize: "1 gyro wrap",
      image: "/products/falafel-gyro.jpg",
      tags: "falafel,vegetarian,gyro,pita,wrap",
      showInFreshDeals: false,
      isFeatured: false,
      displayPriority: 15,
    },
    {
      name: "Fish Gyro",
      slug: "fish-gyro",
      categorySlug: "gyros",
      unitPrice: "9.99",
      compareAtPrice: "11.49",
      shortDescription: "Crispy seasoned fish fillets wrapped in warm pita with crisp lettuce & house sauce",
      description: "Tender, crispy battered fish wrapped in a warm soft pita with fresh shredded lettuce, juicy tomatoes, and our signature sauce.",
      unitSize: "1 gyro wrap",
      image: "/products/fish-gyro.jpg",
      tags: "fish,seafood,gyro,pita,wrap",
      showInFreshDeals: false,
      isFeatured: false,
      displayPriority: 16,
    },

    // Burgers & Sandwiches
    {
      name: "Cheeseburger",
      slug: "cheeseburger",
      categorySlug: "burgers-sandwiches",
      unitPrice: "7.99",
      compareAtPrice: "9.49",
      shortDescription: "100% halal beef patty with melted cheese, lettuce, tomato & mayo on toasted bun",
      description: "Juicy 100% certified halal beef patty grilled to order, topped with melted American cheese, crisp lettuce, ripe tomato slices, pickles, and mayo on a toasted brioche sesame bun.",
      unitSize: "1 burger",
      image: "/products/cheeseburger.jpg",
      tags: "burger,beef,cheeseburger,halal",
      showInFreshDeals: true,
      isFeatured: false,
      displayPriority: 17,
    },
    {
      name: "Double Cheeseburger",
      slug: "double-cheeseburger",
      categorySlug: "burgers-sandwiches",
      unitPrice: "10.49",
      compareAtPrice: "12.49",
      shortDescription: "Two juicy halal beef patties with double melted cheese, lettuce & tomato",
      description: "Double the flavor! Two grilled halal beef patties layered with two slices of melted American cheese, fresh lettuce, tomato, onions, and house sauce on a toasted bun.",
      unitSize: "1 burger",
      image: "/products/double-cheeseburger.jpg",
      tags: "burger,double,beef,halal",
      showInFreshDeals: false,
      isFeatured: true,
      displayPriority: 18,
    },
    {
      name: "Chicken Sandwich",
      slug: "chicken-sandwich",
      categorySlug: "burgers-sandwiches",
      unitPrice: "8.49",
      compareAtPrice: "9.99",
      shortDescription: "Tender grilled or crispy halal chicken breast on a toasted bun with lettuce & mayo",
      description: "Succulent halal chicken breast, fried golden and crispy, served on a toasted bun with crisp shredded lettuce, sliced pickles, and creamy mayonnaise.",
      unitSize: "1 sandwich",
      image: "/products/chicken-sandwich.jpg",
      tags: "chicken,sandwich,burger,halal",
      showInFreshDeals: false,
      isFeatured: false,
      displayPriority: 19,
    },
    {
      name: "Spicy Chicken Sandwich",
      slug: "spicy-chicken-sandwich",
      categorySlug: "burgers-sandwiches",
      unitPrice: "8.99",
      compareAtPrice: "10.49",
      shortDescription: "Spicy seasoned crispy chicken fillet with hot sauce, pickles & mayo on toasted bun",
      description: "Crispy chicken breast with a kick of cayenne and house spices, topped with spicy mayo, dill pickles, and crisp lettuce on a warm toasted bun.",
      unitSize: "1 sandwich",
      image: "/products/spicy-chicken-sandwich.jpg",
      tags: "spicy,chicken,sandwich,halal",
      showInFreshDeals: true,
      isFeatured: true,
      displayPriority: 20,
    },
    {
      name: "Fish Sandwich",
      slug: "fish-sandwich",
      categorySlug: "burgers-sandwiches",
      unitPrice: "8.49",
      compareAtPrice: "9.99",
      shortDescription: "Crispy battered fish fillet with American cheese and tartar sauce on a bun",
      description: "Golden crispy battered fish fillet topped with melted American cheese and tangy tartar sauce on a toasted bun.",
      unitSize: "1 sandwich",
      image: "/products/fish-sandwich.jpg",
      tags: "fish,sandwich,seafood",
      showInFreshDeals: false,
      isFeatured: false,
      displayPriority: 21,
    },
    {
      name: "Falafel Sandwich",
      slug: "falafel-sandwich",
      categorySlug: "burgers-sandwiches",
      unitPrice: "7.99",
      compareAtPrice: "9.49",
      shortDescription: "Crispy chickpea falafel with tahini, cucumber, tomato & lettuce on toasted bread",
      description: "Freshly prepared falafel patties served sandwich-style with tahini, sliced cucumbers, tomatoes, and greens.",
      unitSize: "1 sandwich",
      image: "/products/falafel-sandwich.jpg",
      tags: "falafel,vegetarian,sandwich",
      showInFreshDeals: false,
      isFeatured: false,
      displayPriority: 22,
    },
    {
      name: "Philly Cheesesteak",
      slug: "philly-cheesesteak",
      categorySlug: "burgers-sandwiches",
      unitPrice: "10.99",
      compareAtPrice: "12.99",
      shortDescription: "Thinly sliced halal ribeye steak grilled with onions, peppers & melted cheese on hero",
      description: "Classic Philadelphia style! Thinly sliced halal steak griddled with sweet onions, green bell peppers, and smothered with melted provolone cheese on a warm toasted hero roll.",
      unitSize: "1 hero sandwich",
      image: "/products/philly-cheesesteak.jpg",
      tags: "cheesesteak,philly,beef,halal,hero",
      showInFreshDeals: true,
      isFeatured: true,
      displayPriority: 23,
    },
    {
      name: "Chicken Cheesesteak",
      slug: "chicken-cheesesteak",
      categorySlug: "burgers-sandwiches",
      unitPrice: "10.49",
      compareAtPrice: "12.49",
      shortDescription: "Chopped halal chicken breast grilled with onions, peppers & gooey cheese on hero",
      description: "Tender chopped chicken breast grilled on the flat top with sautéed onions, bell peppers, and melted cheese on a long toasted sub roll.",
      unitSize: "1 hero sandwich",
      image: "/products/chicken-cheesesteak.jpg",
      tags: "cheesesteak,chicken,halal,hero",
      showInFreshDeals: false,
      isFeatured: false,
      displayPriority: 24,
    },
    {
      name: "The Golden Shawarma",
      slug: "the-golden-shawarma",
      categorySlug: "burgers-sandwiches",
      unitPrice: "11.49",
      compareAtPrice: "13.49",
      shortDescription: "Pressed Arabic-style shawarma wrap toasted to golden perfection with garlic sauce & pickles",
      description: "Authentic pressed Middle Eastern shawarma wrap packed with spiced chicken, crisp pickles, garlic toum, and grilled until golden and crispy.",
      unitSize: "1 wrap",
      image: "/products/golden-shawarma.jpg",
      tags: "shawarma,golden,arabic,wrap,halal",
      showInFreshDeals: false,
      isFeatured: false,
      displayPriority: 25,
    },
    {
      name: "Shawarma Pocket Pita",
      slug: "shawarma-pocket-pita",
      categorySlug: "burgers-sandwiches",
      unitPrice: "10.49",
      compareAtPrice: "11.99",
      shortDescription: "Stuffed pita pocket filled with savory shawarma meat, veggies & tahini",
      description: "Warm pita pocket loaded with freshly carved shawarma meat, shredded cabbage, diced tomatoes, and Shah's famous sauces.",
      unitSize: "1 pita pocket",
      image: "/products/shawarma-pocket-pita.jpg",
      tags: "shawarma,pocket,pita,halal",
      showInFreshDeals: false,
      isFeatured: false,
      displayPriority: 26,
    },

    // Party Wings (6 pcs)
    {
      name: "Sweet Red Chili Wings (6 pcs)",
      slug: "sweet-red-chili-wings",
      categorySlug: "party-wings",
      unitPrice: "8.99",
      compareAtPrice: "10.49",
      shortDescription: "6 crispy halal wings glazed in sweet and spicy red chili sauce",
      description: "Six jumbo halal chicken wings fried crispy and tossed in our sweet and tangy red chili glaze. Served with celery and dipping sauce.",
      unitSize: "6 pcs",
      image: "/products/wings-sweet-chili.jpg",
      tags: "wings,chicken,sweet-chili,party-wings",
      showInFreshDeals: false,
      isFeatured: false,
      displayPriority: 27,
    },
    {
      name: "Lemon Pepper Wings (6 pcs)",
      slug: "lemon-pepper-wings",
      categorySlug: "party-wings",
      unitPrice: "8.99",
      compareAtPrice: "10.49",
      shortDescription: "6 crispy halal wings dusted with zesty lemon pepper seasoning",
      description: "Six golden crispy halal wings seasoned generously with tangy lemon zest and cracked black pepper.",
      unitSize: "6 pcs",
      image: "/products/wings-lemon-pepper.jpg",
      tags: "wings,lemon-pepper,chicken,party-wings",
      showInFreshDeals: false,
      isFeatured: false,
      displayPriority: 28,
    },
    {
      name: "Buffalo Wings (6 pcs)",
      slug: "buffalo-wings",
      categorySlug: "party-wings",
      unitPrice: "8.99",
      compareAtPrice: "10.49",
      shortDescription: "6 classic crispy halal wings tossed in spicy cayenne buffalo sauce",
      description: "Six crispy fried wings coated in fiery, tangy traditional buffalo sauce. Served with creamy white dipping sauce.",
      unitSize: "6 pcs",
      image: "/products/wings-buffalo.jpg",
      tags: "wings,buffalo,spicy,chicken,party-wings",
      showInFreshDeals: true,
      isFeatured: true,
      displayPriority: 29,
    },
    {
      name: "Garlic Parmesan Wings (6 pcs)",
      slug: "garlic-parmesan-wings",
      categorySlug: "party-wings",
      unitPrice: "8.99",
      compareAtPrice: "10.49",
      shortDescription: "6 crispy halal wings tossed in rich roasted garlic and aged parmesan",
      description: "Six crispy fried wings smothered in savory garlic butter sauce and dusted with grated parmesan cheese.",
      unitSize: "6 pcs",
      image: "/products/wings-garlic-parm.jpg",
      tags: "wings,garlic-parm,chicken,party-wings",
      showInFreshDeals: false,
      isFeatured: false,
      displayPriority: 30,
    },
    {
      name: "BBQ Chipotle Honey Wings (6 pcs)",
      slug: "bbq-chipotle-honey-wings",
      categorySlug: "party-wings",
      unitPrice: "8.99",
      compareAtPrice: "10.49",
      shortDescription: "6 crispy halal wings glazed with smoky chipotle and sweet golden honey",
      description: "Six crispy wings drenched in a smoky sweet BBQ chipotle glaze with natural honey.",
      unitSize: "6 pcs",
      image: "/products/wings-bbq-honey.jpg",
      tags: "wings,bbq,chipotle,honey,chicken",
      showInFreshDeals: false,
      isFeatured: false,
      displayPriority: 31,
    },

    // Sides
    {
      name: "Pakora Chips",
      slug: "pakora-chips",
      categorySlug: "sides",
      unitPrice: "4.99",
      compareAtPrice: "5.99",
      shortDescription: "Crispy spiced chickpea batter fritter chips served with dipping chutney",
      description: "Authentic crunchy spiced fritters made from chickpea flour, herbs, and spices, fried golden brown and served hot.",
      unitSize: "1 order",
      image: "/products/pakora-chips.jpg",
      tags: "sides,pakora,chips,halal",
      showInFreshDeals: false,
      isFeatured: false,
      displayPriority: 32,
    },
    {
      name: "Baklava (2 pcs)",
      slug: "baklava",
      categorySlug: "sides",
      unitPrice: "3.99",
      compareAtPrice: "4.99",
      shortDescription: "Traditional flaky phyllo pastry layered with crushed nuts and sweet honey syrup (2 pcs)",
      description: "Delicate golden phyllo dough layers packed with chopped walnuts, sweetened with aromatic honey syrup and a hint of rosewater.",
      unitSize: "2 pcs",
      image: "/products/baklava.jpg",
      tags: "sides,dessert,baklava,sweet",
      showInFreshDeals: true,
      isFeatured: false,
      displayPriority: 33,
    },
    {
      name: "Fresh Cut Fries",
      slug: "fresh-cut-fries",
      categorySlug: "sides",
      unitPrice: "4.49",
      compareAtPrice: "5.49",
      shortDescription: "Crispy golden french fries seasoned with Shah's special spice blend",
      description: "Fresh cut potatoes fried to a crisp golden crunch, tossed with Shah's special seasoning salt. Served with ketchup and white sauce.",
      unitSize: "1 order",
      image: "/products/fries.jpg",
      tags: "sides,fries,french-fries",
      showInFreshDeals: false,
      isFeatured: false,
      displayPriority: 34,
    },
    {
      name: "Chicken Nuggets (6 pcs)",
      slug: "chicken-nuggets",
      categorySlug: "sides",
      unitPrice: "5.49",
      compareAtPrice: "6.49",
      shortDescription: "6 crispy all-white meat halal chicken nuggets with choice of dipping sauce",
      description: "Six golden breaded halal chicken nuggets, fried tender and juicy on the inside, crunchy on the outside.",
      unitSize: "6 pcs",
      image: "/products/chicken-nuggets.jpg",
      tags: "sides,nuggets,chicken",
      showInFreshDeals: false,
      isFeatured: false,
      displayPriority: 35,
    },
    {
      name: "Whole Pita Bread",
      slug: "whole-pita-bread",
      categorySlug: "sides",
      unitPrice: "1.99",
      compareAtPrice: "2.49",
      shortDescription: "Freshly warmed, soft and fluffy pita bread round",
      description: "One whole round of soft, freshly warmed Greek pita bread, perfect for scooping rice, salad, and meat.",
      unitSize: "1 piece",
      image: "/products/whole-pita.jpg",
      tags: "sides,pita,bread",
      showInFreshDeals: false,
      isFeatured: false,
      displayPriority: 36,
    },
    {
      name: "Hummus with Pita",
      slug: "hummus-with-pita",
      categorySlug: "sides",
      unitPrice: "5.99",
      compareAtPrice: "6.99",
      shortDescription: "Creamy chickpea hummus with extra virgin olive oil, paprika & warm sliced pita",
      description: "Smooth house-made chickpea hummus blended with tahini, garlic, lemon juice, drizzled with olive oil and served with warm toasted pita.",
      unitSize: "1 order",
      image: "/products/hummus-pita.jpg",
      tags: "sides,hummus,pita,vegetarian",
      showInFreshDeals: false,
      isFeatured: false,
      displayPriority: 37,
    },
    {
      name: "Loaded Chips",
      slug: "loaded-chips",
      categorySlug: "sides",
      unitPrice: "6.99",
      compareAtPrice: "8.49",
      shortDescription: "Crispy fries topped with melted cheese, jalapenos, white sauce & choice of chicken or gyro",
      description: "A mountain of crispy seasoned fries topped with melted cheese sauce, chopped meat, diced jalapenos, and drizzled with Shah's white and hot sauce.",
      unitSize: "1 order",
      image: "/products/loaded-chips.jpg",
      tags: "sides,loaded-chips,fries,specialty",
      showInFreshDeals: false,
      isFeatured: false,
      displayPriority: 38,
    },

    // Drinks
    {
      name: "Soda Can (12 oz)",
      slug: "soda-can",
      categorySlug: "drinks",
      unitPrice: "1.50",
      compareAtPrice: "2.00",
      shortDescription: "Cold canned soda (Coke, Diet Coke, Sprite, Ginger Ale, Fanta)",
      description: "Ice-cold 12 oz aluminum can of your favorite refreshing carbonated soft drink.",
      unitSize: "1 can",
      image: "/products/soda-can.jpg",
      tags: "drinks,soda,beverage",
      showInFreshDeals: false,
      isFeatured: false,
      displayPriority: 39,
    },
    {
      name: "Soda Bottle (20 oz)",
      slug: "soda-bottle",
      categorySlug: "drinks",
      unitPrice: "2.50",
      compareAtPrice: "3.00",
      shortDescription: "Chilled 20 oz resealable bottle of soda",
      description: "Chilled 20 oz bottle of soda available in popular refreshing flavors.",
      unitSize: "1 bottle",
      image: "/products/soda-bottle.jpg",
      tags: "drinks,soda,bottle",
      showInFreshDeals: false,
      isFeatured: false,
      displayPriority: 40,
    },
    {
      name: "Bottled Water (16.9 oz)",
      slug: "bottled-water",
      categorySlug: "drinks",
      unitPrice: "1.50",
      compareAtPrice: "2.00",
      shortDescription: "Pure refreshing cold spring water bottle",
      description: "Pure, chilled natural spring water in a convenient 16.9 oz bottle.",
      unitSize: "1 bottle",
      image: "/products/water-bottle.jpg",
      tags: "drinks,water",
      showInFreshDeals: false,
      isFeatured: false,
      displayPriority: 41,
    },
    {
      name: "Snapple Iced Tea (16 oz)",
      slug: "snapple",
      categorySlug: "drinks",
      unitPrice: "2.50",
      compareAtPrice: "3.00",
      shortDescription: "Real brewed Snapple iced tea (Lemon, Peach, Mango Madness, Kiwi Strawberry)",
      description: "Crisp and flavorful real-brewed iced tea made from the best stuff on Earth.",
      unitSize: "1 bottle",
      image: "/products/snapple.jpg",
      tags: "drinks,snapple,tea",
      showInFreshDeals: false,
      isFeatured: false,
      displayPriority: 42,
    },
    {
      name: "Red Bull Energy Drink (8.4 oz)",
      slug: "red-bull",
      categorySlug: "drinks",
      unitPrice: "3.50",
      compareAtPrice: "4.00",
      shortDescription: "Chilled 8.4 oz can of Red Bull energy drink",
      description: "Vitalizes body and mind with premium taurine and B-group vitamins.",
      unitSize: "1 can",
      image: "/products/red-bull.jpg",
      tags: "drinks,energy,red-bull",
      showInFreshDeals: false,
      isFeatured: false,
      displayPriority: 43,
    },

    // Catering
    {
      name: "Shah's Halal Catering Platter",
      slug: "shahs-halal-catering-platter",
      categorySlug: "catering",
      unitPrice: "89.99",
      compareAtPrice: "99.99",
      shortDescription: "Large party tray feeds 8-10 people: choice of chicken, lamb, or combo with rice, salad, pita & sauces",
      description: "Perfect for family gatherings, office lunches, and celebrations! Includes a full catering tray of your choice of grilled chicken, gyro, or combo, a full tray of spiced basmati rice, a bowl of crisp Mediterranean garden salad, a stack of warm pita bread rounds, and 8 oz bottles of our famous Shah's white and hot sauces.",
      unitSize: "Feeds 8-10 people",
      image: "/products/catering.jpg",
      tags: "catering,party,family,platter,halal",
      showInFreshDeals: false,
      isFeatured: true,
      displayPriority: 44,
    },
  ];

  for (const item of productList) {
    const categoryId = categoryMap.get(item.categorySlug);
    if (!categoryId) continue;

    const [insertedProduct] = await db
      .insert(schema.products)
      .values({
        name: item.name,
        slug: item.slug,
        description: item.description,
        shortDescription: item.shortDescription,
        categoryId,
        supplierId,
        unitPrice: item.unitPrice,
        compareAtPrice: item.compareAtPrice,
        currency: "USD",
        unitType: "each",
        unitSize: item.unitSize,
        minimumOrderQuantity: 1,
        image: item.image,
        origin: "USA",
        grade: "premium",
        organic: false,
        status: "active",
        marketplaceVisible: true,
        showInFreshDeals: item.showInFreshDeals,
        isFeatured: item.isFeatured,
        displayPriority: item.displayPriority,
        tags: item.tags,
      })
      .returning();

    // Create inventory record with plenty of ready stock
    await db.insert(schema.inventory).values({
      productId: insertedProduct.id,
      supplierId,
      quantityOnHand: 250,
      quantityReserved: 10,
      quantityAvailable: 240,
      reorderLevel: 25,
      reorderQuantity: 100,
      warehouseLocation: "KITCHEN-LINE-1",
      status: "in_stock",
      isActive: true,
    });
  }

  console.log(`  ✓ ${productList.length} products and inventory records created`);
  console.log("✅ Shah's Halal Food catalog successfully seeded!");
  await pool.end();
  process.exit(0);
}

seed().catch((err) => {
  console.error("❌ Seed failed:", err);
  pool.end();
  process.exit(1);
});
